version: 2

jobs:

  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/Chiron1991/feed-squirrel
    steps:
      - checkout
      - run: go mod download
      - run: go test -v ./backend/*/